on:
    push:
    workflow_dispatch:

jobs:
  compare:
        name: Compares models https://docs.gptscript.ai/alternative-model-providers
        runs-on: ubuntu-latest
        steps:
        - uses: cpanato/gptscript-installer@main
        - uses: actions/checkout@v4
        - shell: bash
          name: Mistral
          run: make mistral
          env:
            GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        - shell: bash
          name: OpenAI
          run: make openai
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: Anthropic
          run: make anthropic
          env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
