on:
    push:
    workflow_dispatch:

jobs:
  compare:
        name: Compares models https://docs.gptscript.ai/alternative-model-providers
        runs-on: ubuntu-latest
        steps:
        - uses: cpanato/gptscript-installer@main
        - uses: actions/checkout@v4
        - shell: bash
          name: Mistral
          run: ./mistral.sh
          env:
            GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: OpenAI
          run: ./openai.sh
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: Anthropic
          run: ./anthropic.sh
          env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: Sanity test answers
          run: cd test; ./test.sh | sh
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        - name: Generate report
          run: go run generate-report/main.go > report.html

        - name: Upload report as artifact
          uses: actions/upload-artifact@v4
          with:
            name: report
            path: report.html
