on:
    push:
    workflow_dispatch:

# We try save gptscript runs to save on $$$
env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

# Needed for deploying to report to Github pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compare:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        name: Compares models https://docs.gptscript.ai/alternative-model-providers
        runs-on: ubuntu-latest
        steps:
        - uses: cpanato/gptscript-installer@main
        - uses: actions/checkout@v4


        - uses: actions/cache@v4
          id: cache
          with:
            path: $XDG_CACHE_HOME/gptscript
            key: ${{ runner.os }}-${{ hashFiles('*.gpt') }}

        - run: ls $XDG_CACHE_HOME/gptscript || true

        - shell: bash
          name: Mistral
          run: ./mistral.sh
          env:
            GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: OpenAI
          run: ./openai.sh
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: Anthropic
          run: ./anthropic.sh
          env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        - shell: bash
          name: Sanity test answers
          run: cd test; ./test.sh | sh
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        # debugging Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
        - run: ls $XDG_CACHE_HOME/gptscript || true

        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Generate report
          run: mkdir "_site" && go run generate-report/main.go > _site/index.html
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
