on:
    push:
    workflow_dispatch:

# We try save gptscript runs to save on $$$
env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

# Needed for deploying the report to Github pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compare:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        name: Testing models
        runs-on: ubuntu-latest
        steps:
        - uses: cpanato/gptscript-installer@main
        - uses: actions/checkout@v4

        - uses: actions/cache@v4
          with:
            path: ${{ env.XDG_CACHE_HOME }}
            key: ${{ runner.os }}-${{ hashFiles('*.gpt') }}

        - shell: bash
          name: Run tests
          run: ./test.sh
          env:
            GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

        - shell: bash
          name: Sanity test answers
          run: ./test/test.sh
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Generate report
          run: mkdir "_site" && cd generate-report && go run . > ../_site/index.html
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4